[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Override Netlify's default timeout for serverless functions
# The default is 10 seconds, but we need 5 minutes for GPT-5
[functions]
  # Use esbuild for better performance
  node_bundler = "esbuild"

# Configure function timeouts using the correct Netlify syntax
[functions."generate-ai-code-stream"]
  timeout = 300

[functions."scrape-screenshot"]
  timeout = 60

[functions."restart-vite"]
  timeout = 30
