# Cloudflare Pages configuration for open-lovable
name = "open-lovable"
compatibility_date = "2024-08-16"
compatibility_flags = ["nodejs_compat"]

# Pages Functions configuration
[functions]
directory = "app/api"

# Environment variables (will be set in Cloudflare dashboard)
[vars]
NODE_ENV = "production"

# KV namespaces (if needed later)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"

# Durable Objects (if needed later)
# [[durable_objects.bindings]]
# name = "MY_DO"
# class_name = "MyDurableObject"

# R2 storage (if needed later)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
