# Cloudflare Workers configuration for open-lovable
name = "open-lovable"
compatibility_date = "2024-08-16"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
main = "src/index.ts"

[build]
command = "npm run build:worker"

[env.production.vars]
NODE_ENV = "production"
# Add your API keys and other sensitive variables here
# These are just placeholders - set real values in dashboard
# ANTHROPIC_API_KEY = "your-api-key-here"
# E2B_API_KEY = "your-e2b-key-here"
# OPENAI_API_KEY = "your-openai-key-here"
# GROQ_API_KEY = "your-groq-key-here"

