# Cloudflare Pages configuration for open-lovable frontend
[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "app/api"

[vars]
NODE_ENV = "production"


