# Cloudflare Pages configuration for frontend
[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"

# Functions configuration (if you want to use Pages Functions for some routes)
[functions]
directory = "app/api"

# Environment variables
[vars]
NODE_ENV = "production"
# Add your API keys here for frontend use (if needed)
# ANTHROPIC_API_KEY = "your-api-key-here"


